apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: cluster.local
  providerSpec:
    value:
      apiVersion: packetproviderconfig/v1alpha1
      kind: PacketClusterProviderSpec
      project: example
      facility: nrt1
      plan: t1.small.x86
      secretRef: example-packet-secret
